#!/usr/bin/env bash
set -euo pipefail

DRY_RUN=0
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$ROOT_DIR/.project-setup/logs"
LOG_FILE="$LOG_DIR/bootstrap-project.log"

usage() {
  echo "Usage: $0 [--dry-run]"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

log() {
  echo "$1"
  if [ "$DRY_RUN" -eq 0 ]; then
    mkdir -p "$LOG_DIR"
    printf "%s %s\n" "$(date '+%Y-%m-%d %H:%M:%S %Z')" "$1" >> "$LOG_FILE"
  fi
}

log "Bootstrapping project"
if [ "$DRY_RUN" -eq 1 ]; then
  log "Mode: dry-run"
  "$ROOT_DIR/scripts/check-prereqs.sh" --dry-run
  if [ ! -f "$ROOT_DIR/docs/local-assumptions.md" ]; then
    log "Would create docs/local-assumptions.md (gitignored, machine-local -- see .gitignore)"
  fi
else
  log "Mode: apply"
  mkdir -p "$ROOT_DIR/.project-setup/logs"
  "$ROOT_DIR/scripts/check-prereqs.sh"

  # docs/local-assumptions.md is gitignored (its content is meant to vary
  # per machine, same class as docs/session-log.md), so verify-project.sh's
  # check for it can only pass on a fresh clone if bootstrap actually
  # creates it -- confirmed missing here until 2026-09-04, meaning
  # verify-project.sh's own reproducibility check had never actually been
  # exercised end-to-end on a truly blank machine before this fix.
  if [ ! -f "$ROOT_DIR/docs/local-assumptions.md" ]; then
    log "Creating docs/local-assumptions.md (gitignored, machine-local)"
    cat > "$ROOT_DIR/docs/local-assumptions.md" <<'EOF'
# Local Assumptions

This repo is documentation-only except for `scripts/eco_collector.py` /
`scripts/eco_checker.py` / `scripts/eco.sh` (Phase 0 of
[docs/interactive-plan.md](interactive-plan.md)). This file is
machine-local (gitignored, generated by `scripts/bootstrap-project.sh`,
not shipped in git) -- edit it freely for your own environment.

## Assumed present

- `python3` (stdlib only -- no third-party packages required).
- `git`, on `PATH`.
- `gh` (GitHub CLI), on `PATH` and authenticated -- optional in practice:
  the collector degrades every GitHub-sourced field to
  `source: "unavailable"` rather than failing when `gh` is missing,
  unauthenticated, or offline.
- `bash` for `scripts/eco.sh` and the other `scripts/*.sh` wrappers.

## Assumed about sibling checkouts

The six component repos are assumed to live as git checkouts, either as
siblings of this repo under `factory-output/` or (veil-observatory only)
at `~/Development/veil-observatory` -- overridable per-component via env
vars, see `scripts/eco-components.json`. Not required for
`verify-project.sh` to pass: a blank machine with none of the sibling
repos checked out still passes, with every repo-dependent field reported
as unavailable rather than failing the run.
EOF
  fi
fi

log "TODO: add remaining project-specific setup steps after they are documented."
